<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Fase 5: tabla ext_log_entries de Gedmo Loggable (App\Entity\LogEntry) — auditoría automática de
 * cambios en entidades administrativas (User, Role, PaymentGateway, ExchangeRateProvider) en vez
 * de depender de que cada servicio llame manualmente a un log. La columna `data` se mapea como
 * JSON (no como el "array" serializado en PHP que trae Gedmo por defecto, un tipo de Doctrine DBAL
 * eliminado en la versión 4 que usa este proyecto).
 */
final class Version20260716164925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fase 5: tabla ext_log_entries para la auditoría Gedmo Loggable de entidades administrativas.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE ext_log_entries (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              action VARCHAR(8) NOT NULL,
              logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              object_id VARCHAR(64) DEFAULT NULL,
              object_class VARCHAR(191) NOT NULL,
              version INT NOT NULL,
              data JSON DEFAULT NULL,
              username VARCHAR(191) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON ext_log_entries (username)');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ext_log_entries');
    }
}
