# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.encryption_key: '%env(ENCRYPTION_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\:
        resource: '../src/Repository/'
        tags: ['doctrine.repository_service']

    App\Services\:
        resource: '../src/Services/'
        tags: ['service_subscriber']

    App\Services\Notifications\OpenWaService:
        arguments:
            $apikey: '%env(OPENWA_APIKEY)%'
            $baseUrl: '%env(OPENWA_URL)%'
            $sessionId: '%env(OPENWA_SESSIONS)%'

    App\Services\PermissionService:
        arguments:
            $projectDir: '%kernel.project_dir%'



    App\EventSubscriber\:
        resource: '../src/EventSubscriber/'
        tags: ['kernel.event_subscriber']

    App\EventListener\:
        resource: '../src/EventListener/'
        exclude:
            - '../src/EventListener/ApiTransactionLogListener.php'
            - '../src/EventListener/RequireScopeListener.php'
            - '../src/EventListener/ApiExceptionListener.php'
        tags: ['kernel.event_listener']

    App\EventListener\ApiTransactionLogListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\EventListener\RequireScopeListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 32 }

    App\Security\:
        resource: '../src/Security/'

    App\DTO\:
        resource: '../src/DTO/'
